# Generated by Django 6.0 on 2025-12-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of name",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="professor",
            index=models.Index(fields=["slug"], name="reviews_pro_slug_daf0e2_idx"),
        ),
    ]
